apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-a-system
  labels:
    app: api-a-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-a-system
  template:
    metadata:
      labels:
        app: api-a-system
    spec:
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      nodeSelector:
        kubernetes.azure.com/mode: system
      containers:
      - name: api
        image: iacws2evgacr.azurecr.io/apia:v1
        imagePullPolicy: IfNotPresent
        resources: {}
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3    
        readinessProbe:
          httpGet:
            path: /readiness
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
