apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab4-task7
  labels:
    app: lab4-task7
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab4-task7
  template:
    metadata:
      labels:
        app: lab4-task7
    spec:
      containers:
      - name: api
        image: iacws2evgacr.azurecr.io/apia:v1
        imagePullPolicy: IfNotPresent
        resources: {}
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"