---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  interval: 1m0s
  values:
    controller:
      admissionWebhooks:
        patch:
          nodeSelector:
            beta.kubernetes.io/os: linux
      image:
        tag: v1.0.4
      nodeSelector:
        beta.kubernetes.io/os: linux
      replicaCount: 1
      service:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        loadBalancerIP: 10.11.1.10
    defaultBackend:
      nodeSelector:
        beta.kubernetes.io/os: linux

