apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab4-task1
  labels:
    app: lab4-task1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab4-task1
  template:
    metadata:
      labels:
        app: lab4-task1
    spec:
      containers:
      - name: api
        image: iacws2evgacr.azurecr.io/apia:v1
        imagePullPolicy: IfNotPresent
        resources: {}