apiVersion: v1
kind: Pod
metadata:
  name: curl
spec:
  containers:
    - name: curl
      image: "radial/busyboxplus:curl"      
      command:
        - sleep
        - "3600"
      resources:
        limits:
          cpu: "0.2"
          memory: "10Mi"
  restartPolicy: Always
