apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-a
  labels:
    app: api-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-a
  template:
    metadata:
      labels:
        app: api-a
    spec:
      containers:
      - name: api
        image: iacws5t2jx2i6odz7gkacr.azurecr.io/apia:v2
        imagePullPolicy: IfNotPresent
        resources: 
          requests:
            cpu: 200m
          limits:
            cpu: 500m
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3    
---
apiVersion: v1
kind: Service
metadata:
  name: api-a-service
  labels:
    app: api-a
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: api-a
  type: ClusterIP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-a-hpa
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-a
  targetCPUUtilizationPercentage: 50 # target CPU utilization
